import { Haiku } from './../src/haiku.js';


describe('Haiku', () => {

  const line1 = "I close my eyes and";
  const line2 = "try to imagine all the";
  const line3 = "impossible things";

  test('Correctly determine if 3 strings a create haiku poem object', ()=> {
    let haiku = new Haiku(line1,line2,line3);
    expect(haiku.line1).toEqual("I close my eyes and");
    expect(haiku.line2).toEqual("try to imagine all the");
    expect(haiku.line3).toEqual("impossible things");
  });
  test('Correctly create an array of the line 1 string within haiku object', ()=> {
    let haiku = new Haiku(line1,line2,line3);
    let haikuArray = haiku.line1Array;
    expect(haikuArray).toEqual(["I","close","my","eyes","and"]);
  });
  test('Correctly display the number of vowels in vowelCount property', ()=> {
    let haiku = new Haiku(line1,line2,line3);
    let haiku2 = new Haiku("Haikus are easy","But sometimes they don't make sense","Refrigerator");
    let haiku3 = new Haiku("x xxxx xxx xxxx xxxx",line2,line3);
    let haiku4 = new Haiku("But sometimes they don't make sense","Haikus are easy","Arrrg greee moooat beu jess");
    let haiku5 = new Haiku("monkeys with eyes say yes aboves",line2,line3);
    let haiku6 = new Haiku("carefree driveway lifeboat stagecraft widebody",line2,line3);
    haiku.getVowels();
    haiku2.getVowels();
    haiku3.getVowels();
    haiku4.getVowels();
    haiku5.getVowels();
    haiku6.getVowels();
    expect(haiku.vowelCount).toEqual(8);
    expect(haiku2.vowelCount).toEqual(8);
    expect(haiku3.vowelCount).toEqual(0);
    expect(haiku4.vowelCount).toEqual(12);
    expect(haiku5.vowelCount).toEqual(14);
    expect(haiku6.vowelCount).toEqual(19);
  });
  test('Correctly display the number of vowels that have a silent e at the end of the word', ()=> {
    let haiku = new Haiku("I close my eyes and",line2,line3);
    let haiku2 = new Haiku("Haikus are easy","But sometimes they don't make sense","Refrigerator");
    let haiku3 = new Haiku("x xxxx xxx xxxx xxxx",line2,line3);
    let haiku4 = new Haiku("But sometimes they don't make sense","Haikus are easy","Arrrg greee moooat beu jess");
    let haiku5 = new Haiku("monkeys with eyes say yes aboves",line2,line3);
    let haiku6 = new Haiku("carefree driveway lifeboat stagecraft widebody",line2,line3);
    haiku.getSilentE();
    haiku2.getSilentE();
    haiku3.getSilentE();
    haiku4.getSilentE();
    haiku5.getSilentE();
    haiku6.getSilentE();
    let silentETest = haiku.silentE;
    let silentETest2 = haiku2.silentE;
    let silentETest3 = haiku3.silentE;
    let silentETest4 = haiku4.silentE;
    let silentETest5 = haiku5.silentE;
    let silentETest6 = haiku6.silentE;
    expect(silentETest).toEqual(1);
    expect(silentETest2).toEqual(1);
    expect(silentETest3).toEqual(0);
    expect(silentETest4).toEqual(2);
    expect(silentETest5).toEqual(0);
    expect(silentETest6).toEqual(1);
  });
  test('Correctly identify words in the line1 array that have a two vowel string - also tests for 2 or more consecutive vowels', ()=> {
    let haiku = new Haiku("I close my eyes and",line2,line3);
    let haiku2 = new Haiku("Haikus are easy","But sometimes they don't make sense","Refrigerator");
    let haiku3 = new Haiku("x xxxx xxx xxxx xxxx",line2,line3);
    let haiku4 = new Haiku("But sometimes they don't make sense","Haikus are easy","Arrrg greee moooat beu jess");
    let haiku5 = new Haiku("monkeys with eyes say yes aboves",line2,line3);
    let haiku6 = new Haiku("carefree driveway lifeboat stagecraft widebody",line2,line3);
    haiku.getDoubleVowel();
    haiku2.getDoubleVowel();
    haiku3.getDoubleVowel();
    haiku4.getDoubleVowel();
    haiku5.getDoubleVowel();
    haiku6.getDoubleVowel();
    let doubleVowelWordTest = haiku.doubleVowel;
    let doubleVowelWordTest2 = haiku2.doubleVowel;
    let doubleVowelWordTest3 = haiku3.doubleVowel;
    let doubleVowelWordTest4 = haiku4.doubleVowel;
    let doubleVowelWordTest5 = haiku5.doubleVowel;
    let doubleVowelWordTest6 = haiku6.doubleVowel;
    expect(doubleVowelWordTest).toEqual(1);
    expect(doubleVowelWordTest2).toEqual(2);
    expect(doubleVowelWordTest3).toEqual(0);
    expect(doubleVowelWordTest4).toEqual(1);
    expect(doubleVowelWordTest5).toEqual(4);
    expect(doubleVowelWordTest6).toEqual(2);
  });
  test('Correctly identify word with ending es', ()=> {
    let haiku = new Haiku("I close my eyes and",line2,line3);
    let haiku2 = new Haiku("Haikus are easy","But sometimes they don't make sense","Refrigerator");
    let haiku3 = new Haiku("x xxxx xxx xxxx xxxx",line2,line3);
    let haiku4 = new Haiku("But sometimes they don't make sense","Haikus are easy","Arrrg greee moooat beu jess");
    let haiku5 = new Haiku("monkeys with eyes say yes aboves",line2,line3);
    let haiku6 = new Haiku("carefree driveway lifeboat stagecraft widebody",line2,line3);
    haiku.getLastTwoCharEs();
    haiku2.getLastTwoCharEs();
    haiku3.getLastTwoCharEs();
    haiku4.getLastTwoCharEs();
    haiku5.getLastTwoCharEs();
    haiku6.getLastTwoCharEs();
    let wordTest = haiku.lastTwoCharEs;
    let wordTest2 = haiku2.lastTwoCharEs;
    let wordTest3 = haiku3.lastTwoCharEs;
    let wordTest4 = haiku4.lastTwoCharEs;
    let wordTest5 = haiku5.lastTwoCharEs;
    let wordTest6 = haiku6.lastTwoCharEs;
    expect(wordTest).toEqual(1);
    expect(wordTest2).toEqual(0);
    expect(wordTest3).toEqual(0);
    expect(wordTest4).toEqual(1);
    expect(wordTest5).toEqual(3);
    expect(wordTest6).toEqual(0);
  });
  test('Correctly break compound words', ()=> {
    let haiku = new Haiku("I close my eyes and",line2,line3);
    let haiku2 = new Haiku("Haikus are easy","But sometimes they don't make sense","Refrigerator");
    let haiku3 = new Haiku("x xxxx xxx xxxx xxxx",line2,line3);
    let haiku4 = new Haiku("But sometimes they don't make sense","Haikus are easy","Arrrg greee moooat beu jess");
    let haiku5 = new Haiku("monkeys with eyes say yes aboves",line2,line3);
    let haiku6 = new Haiku("carefree driveway lifeboat stagecraft widebody",line2,line3);
    haiku.getSilentCompounds();
    haiku2.getSilentCompounds();
    haiku3.getSilentCompounds();
    haiku4.getSilentCompounds();
    haiku5.getSilentCompounds();
    haiku6.getSilentCompounds();
    let compoundFix = haiku.silentCompound;
    let compoundFix2 = haiku2.silentCompound;
    let compoundFix3 = haiku3.silentCompound;
    let compoundFix4 = haiku4.silentCompound;
    let compoundFix5 = haiku5.silentCompound;
    let compoundFix6 = haiku6.silentCompound;
    expect(compoundFix).toEqual(0);
    expect(compoundFix2).toEqual(0);
    expect(compoundFix3).toEqual(0);
    expect(compoundFix4).toEqual(1);
    expect(compoundFix5).toEqual(0);
    expect(compoundFix6).toEqual(5);
  });
  test('Correctly tally the vowel exceptions on a line of a haiku object', ()=> {
    let haiku = new Haiku("I close my eyes and",line2,line3);
    let haiku2 = new Haiku("Haikus are easy","But sometimes they don't make sense","Refrigerator");
    let haiku3 = new Haiku("x xxxx xxx xxxx xxxx",line2,line3);
    let haiku4 = new Haiku("But sometimes they don't make sense","Haikus are easy","Arrrg greee moooat beu jess");
    let haiku5 = new Haiku("monkeys with eyes say yes aboves",line2,line3);
    let haiku6 = new Haiku("carefree driveway lifeboat stagecraft widebody",line2,line3);
    haiku.getVowelExceptions();
    haiku2.getVowelExceptions();
    haiku3.getVowelExceptions();
    haiku4.getVowelExceptions();
    haiku5.getVowelExceptions();
    haiku6.getVowelExceptions();
    let checkExceptions = haiku.vowelExceptions;
    let checkExceptions2 = haiku2.vowelExceptions;
    let checkExceptions3 = haiku3.vowelExceptions;
    let checkExceptions4 = haiku4.vowelExceptions;
    let checkExceptions5 = haiku5.vowelExceptions;
    let checkExceptions6 = haiku6.vowelExceptions;
    expect(checkExceptions).toEqual(3);
    expect(checkExceptions2).toEqual(3);
    expect(checkExceptions3).toEqual(0);
    expect(checkExceptions4).toEqual(5);
    expect(checkExceptions5).toEqual(7);
    expect(checkExceptions6).toEqual(8);
  });
  test('Correctly display the number of vowels in vowelCount property', ()=> {
    let haiku = new Haiku(line1,line2,line3);
    let haiku2 = new Haiku("Haikus are easy","But sometimes they don't make sense","Refrigerator");
    let haiku3 = new Haiku("x xxxx xxx xxxx xxxx",line2,line3);
    let haiku4 = new Haiku("But sometimes they don't make sense","Haikus are easy","Arrrg greee moooat beu jess");
    let haiku5 = new Haiku("monkeys with eyes say yes aboves",line2,line3);
    let haiku6 = new Haiku("carefree driveway lifeboat stagecraft widebody",line2,line3);
    haiku.getVowels();
    haiku2.getVowels();
    haiku3.getVowels();
    haiku4.getVowels();
    haiku5.getVowels();
    haiku6.getVowels();
    expect(haiku.vowelCount).toEqual(8);
    expect(haiku2.vowelCount).toEqual(8);
    expect(haiku3.vowelCount).toEqual(0);
    expect(haiku4.vowelCount).toEqual(12);
    expect(haiku5.vowelCount).toEqual(14);
    expect(haiku6.vowelCount).toEqual(19);
  });
});
